# THIS SCRIPT WAS GENERATED BY CHAT GPT
import socket

class tcp_sender:
    def __init__(self, host, port):
        self.host = host
        self.port = port
        self.socket = None

    def connect(self)-> bool:
        try:
            self.socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            self.socket.connect((self.host, self.port))
            return True
        except Exception as e:
            print(f"Connection error: {e}")
            return False

    def disconnect(self):
        if self.socket:
            self.socket.close()

    def send(self, message)-> bool:
        print(f"sending \"{message}\" to {self.host}:{self.port}")
        if not self.connect():
            print(f"Cannot connect to {self.host}:{self.port}")
        if self.socket:
            try:
                self.socket.send(message.encode())
                self.disconnect()
                return True
            except Exception as e:
                print(f"Send error: {e}")
        self.disconnect()
        return False