# Use an Ubuntu base image
FROM ubuntu:20.04

# Set non-interactive mode for apt
ENV DEBIAN_FRONTEND=noninteractive

# Install systemd and other required packages
RUN apt-get update && apt-get install -y systemd systemd-sysv

# Clean up apt cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Enable systemd in the container
RUN (cd /lib/systemd/system/sysinit.target.wants/; \
    for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done) && \
    rm -f /lib/systemd/system/multi-user.target.wants/* && \
    rm -f /etc/systemd/system/*.wants/* && \
    rm -f /lib/systemd/system/local-fs.target.wants/* && \
    rm -f /lib/systemd/system/sockets.target.wants/*udev* && \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl* && \
    rm -f /lib/systemd/system/basic.target.wants/* && \
    rm -f /lib/systemd/system/anaconda.target.wants/*

#sinstall ssh
RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd

# copy public ssh key
COPY ./id_rsa.pub /root/.ssh/authorized_keys

# start systemd and ssh
CMD ["/lib/systemd/systemd", "/usr/sbin/sshd", "-D"]
